### ISSUE TITLE
Keep getting errors when running script

### ISSUE THREAD

**Issue by Trouble-51** [Digiex/M4V-Converter#1]
This is the message i get when trying to convert a MKV file:

Processing directory[1 of 1]: /Users/jos/Downloads/complete/Designated.Survivor.S01E01.1080p.HDTV.x264-CROOKS.1
Processing file[1 of 5]: /Users/jos/Downloads/complete/Designated.Survivor.S01E01.1080p.HDTV.x264-CROOKS.1/designated.survivor.s01e01.1080p.hdtv.x264-crooks.mkv
Converting...
Result: success
Conversion efficiency at 429457914878%; Original=4.0GB; Converted=915MB
Processing file[2 of 5]: /Users/jos/Downloads/complete/Designated.Survivor.S01E01.1080p.HDTV.x264-CROOKS.1/designated.survivor.s01e01.1080p.hdtv.x264-crooks.nfo
File does not have the expected extension, attemtping...
File is missing audio
Processing file[3 of 5]: /Users/jos/Downloads/complete/Designated.Survivor.S01E01.1080p.HDTV.x264-CROOKS.1/Designated.Survivor.S01E01.1080p.HDTV.x264-CROOKS.nzb
File is not convertable

and this last messages is repeated for file 4 and 5

Please help me understand what I am doing wrong

Thanks,

Jos

**Comment by Snookieboy** [comment]
Your trying to send nfo's and nzb's to the MP4 Converter which are not movies.
As you can see the first file which was the actual movie was a success.

In your download client you should clean the following file extensions:
ParIgnoreExt:  .sfv, .nzb, .nfo
ExtCleanupDisk:  .par2, .sfv, _brokenlog.txt

**Comment by Trouble-51** [comment]
Thanks very much for your help!

 

I am a rooky with SABnzbd etc, but you have to start somewhere …

 

This is what the result was:

 

Processing directory[1 of 1]: /Users/jos/Downloads/complete/Designated.Survivor.S01E01.1080p.HDTV.x264-CROOKS English

Processing file[1 of 1]: /Users/jos/Downloads/complete/Designated.Survivor.S01E01.1080p.HDTV.x264-CROOKS English/gU5PmillBk8FsimDscfYm8Tei41Ec3wunS68.mkv

Converting...

Result: success

Conversion efficiency at 446%; Original=4.0GB; Converted=915MB

 

Still have some questions, if you don’t mind:

 

1)       The file gets a very strange name: gU5PmillBk8FsimDscfYm8Tei41Ec3wunS68.mv4. I had expected Designated.Survivor.S01E01.1080p.HDTV.x264.mp4

2)       The file goes to the “completed” directory in downloads and not to my QNAP TV series folder

3)       In the QNAP TV series folder I still get the following file:  Designated Survivor - S01E01 - Pilot HDTV-1080p.mkv

 

What do I have to change in the script or elsewhere?

 

Thanks in advance for your help,

 

Jos

**Comment by xzKinGzxBuRnzx** [comment]
Hello!

If you are using SABnzbd you need to copy/paste the default.conf to M4V-Converter.conf and edit it to your liking. The settings within can be a bit complicated if you don't know what your doing but if you need help I'm here to assist.

If your using NZBGet you can edit the settings from the web interface.

The file ends with .m4v by default simply cause this script is called M4V-Converter. If you prefer you can change this to .mp4 by editing the config option 'EXTENSION' or web interface. Whichever you choose should not effect your ability to play the file as the format by default is still mp4.

The file going to your completed downloads folder is the expected behavior. If your using Sonarr, you probably have the Drone factory folder set to your completed folder.

File names such as "gU5PmillBk8FsimDscfYm8Tei41Ec3wunS68" are common until processed by Sonarr. Sonarr will rename the file to "Designated Survivor - S01E01 - Pilot HDTV-1080p.m4v" and move it into your QNAP TV series folder.

**Comment by Trouble-51** [comment]
Good morning again,

I made a change to where the file should go and it worked but with the following message:

Type	Date	Time	Users	Source IP	Computer name	Content	

Warning	2017/04/05	22:27:28	System	127.0.0.1	localhost	[Media Library] Path parsing failed: /share/CACHEDEV1_DATA/Multimedia/Videos/Designated Survivor/Season 1/_UNPACK_Designated.Survivor.S01E01.1080p.HDTV.x264-CROOKS English/gU5PmillBk8FsimDscfYm8Tei41Ec3wunS68.mkv	

Not sure what this means because this tis what the folder in QNAP shows i.e. the M4V file and a strange folder




The file was converted as follows:

Processing directory[1 of 1]: /Volumes/Multimedia/Videos/Designated Survivor/Season 1
Processing file[1 of 1]: /Volumes/Multimedia/Videos/Designated Survivor/Season 1/Designated Survivor - S01E01 - 1080p.HDTV.x264-CROOKS English.mkv
Converting...
Result: success
Conversion efficiency at 446%; Original=4.0GB; Converted=915MB

However where can I indicate that i don’t want to change the the size of the file as there is a big loss of quality and the episode stutters when playing using Plex to watch the episode on Apple TV?

Thanks again,

Jos

**Comment by xzKinGzxBuRnzx** [comment]
Looking at this path "/share/CACHEDEV1_DATA/Multimedia/Videos/Designated Survivor/Season 1/_UNPACK_Designated.Survivor.S01E01.1080p.HDTV.x264-CROOKS English/gU5PmillBk8FsimDscfYm8Tei41Ec3wunS68.mkv" it appears you have changed a setting and it's putting incomplete/complete downloads into the wrong folder. Take notice that the folder name has _UNPACK_ this means SABnzbd/nzbget was unzipping files still when it got moved.

They should be going to something like this: "/Users/jos/Downloads/complete/Designated.Survivor.S01E01.1080p.HDTV.x264-CROOKS English/gU5PmillBk8FsimDscfYm8Tei41Ec3wunS68.mkv"

Sonarr drone factory folder should be blank, preventing it from constantly polling your download folder looking for new files. It is suppose to pick up automatically when a download is complete and fully post processed.

You can set 'level' and 'profile' to * this should almost always cause it to copy the orginal video source and simply make a new mp4 container instead of mkv.
