### ISSUE TITLE
How to use the scripts after they changed

### ISSUE THREAD

**Issue by tanja84dk** [Digiex/M4V-Converter#14]
I’m sorry to ask how do I use the scripts newest version?

The reason is that I unfortunally have lost the old version and the read me file hasn’t been updated so unfortunally I haven’t been able to figure out how the new script works

**Comment by xzKinGzxBuRnzx** [comment]
I've meant to create a Wiki here but just haven't got around to doing it, hence why I stripped out some of the help messages from the script, but using it really depends on how you want to use it? 

If your looking for the docker version, I've moved it from xzkingzxburnzx/m4v-converter to digiex/mp4. This simplified the name on Docker and now offers builds for x86-64, ARM64, ARMHF. If you want NZBGet included, you can find it at digiex/nzbget and SABnzbd at digiex/sabnzbd. All of which should have latest or testing tags.

You can still just run the script without Docker but it does have a few more dependencies now, 'jq' a JSON parser, 'bc' this is because BASH cannot handle floating point values and 'mediainfo' because there was some data that 'FFprobe' couldn't provide.

A config file is no longer provided but instead created, you can trigger it by simply running the script once. './mp4.sh'
