### ISSUE TITLE
Trying to convert m4v fails with

### ISSUE THREAD

**Issue by geekteq** [Digiex/M4V-Converter#2]
No decoder for stream #0:1, filtering impossible

Stream #0:1 of the file in question looks like this:
    Stream #0:1(eng): Video: none (drmi / 0x696D7264), none(tv, bt709, progressive), 1920x1080, 5121 kb/s, SAR 1:1 DAR 16:9, 25 fps, 25 tbr, 600 tbn, 600 tbc (default)
    Metadata:
      creation_time   : 2017-05-07T12:33:52.000000Z
      handler_name    : Core Media Video

Any help appreciated but not expected :)

MacOS Sierra could be good to know I guess, reproduced on Ubuntu 16.04 as well

**Comment by xzKinGzxBuRnzx** [comment]
Hello! It appears this issue it caused by "Video: none" (decoder). Do you have a full verbose log? Did the script complain the file was missing video or does it make it as far as providing a ffmpeg command but fails?

Also, did you use the provided ffmpeg install script? If not it would be very helpful if you could run 'ffmpeg -codecs' manually and give me the output.

**Comment by geekteq** [comment]
There is video on it but it's "DRM"ed I guess.. the output you get is from FFMPEG (no decode from stream #0:1 filtering impossible. Yes.. I did install with your ffmpeg-install-script as it grabs a patch somewhere and does something I though may be beneficial ;) 

The only verbose output from the script I get is:

./M4V-Converter.sh -v -i ~/Music/iTunes/iTunes\ Media/Movies/movie.m4v -o ~/Desktop/                                                              
Processing file[1 of 1]: /Users/mattias/Music/iTunes/iTunes Media/Movies/movie.m4v
VERBOSE: ffmpeg -threads auto -i "/Users/mattias/Music/iTunes/iTunes Media/Movies/movie.m4v" -progress "/Users/mattias/Desktop/movie.m4v.stats" -map 0:1 -c:v:0 libx264 -preset:0 medium -profile:v:0 main -pix_fmt:0 yuv420p -level:0 4.1 -crf:0 23 -map 0:0 -c:a:0 copy -metadata:s:a:0 "language=deu" -map_metadata -1 -map_chapters -1 -f mp4 -flags +global_header -movflags +faststart -strict -2 -y "/Users/mattias/Desktop/movie.m4v.tmp"
Converting...
Result: failure

And when I run the ffmpeg command line separately it gives the "original" postings error message.

codecs attached.

[ffmpegcodecs.txt](https://github.com/Digiex/M4V-Converter/files/1018027/ffmpegcodecs.txt)

**Comment by xzKinGzxBuRnzx** [comment]
Your right, DRM is the problem. Unfortunately ffmpeg does not have the ability to remove it. I'll add some code to the script to prevent it from even attempting DRM files in the future.

This script was never designed to convert iTunes DRM protected files, just a huge oversight on my part by naming the script m4v-converter rather than mp4-converter. I apologise for the confusion.

**Comment by xzKinGzxBuRnzx** [comment]
https://github.com/Digiex/M4V-Converter/commit/696931919c4d3faf4f44c0be42216608afee8c64
